// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuI-FZ5S0FRjCZJ6oPSDj3CQfqxcsTHtA',
    appId: '1:352835275222:web:08061bad1ad2e3403bfc77',
    messagingSenderId: '352835275222',
    projectId: 'task-manager-b0625',
    authDomain: 'task-manager-b0625.firebaseapp.com',
    storageBucket: 'task-manager-b0625.appspot.com',
    measurementId: 'G-7RQEXRC8XV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcDOdhthXmDRIjPThC2BFt5zziK21cCSM',
    appId: '1:352835275222:android:43b36aa36187aae93bfc77',
    messagingSenderId: '352835275222',
    projectId: 'task-manager-b0625',
    storageBucket: 'task-manager-b0625.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvGX5ca4HGO45vRaKQMdHb6j4izNq7zTA',
    appId: '1:352835275222:ios:5d2c56463bd781553bfc77',
    messagingSenderId: '352835275222',
    projectId: 'task-manager-b0625',
    storageBucket: 'task-manager-b0625.appspot.com',
    iosBundleId: 'com.example.plannerFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvGX5ca4HGO45vRaKQMdHb6j4izNq7zTA',
    appId: '1:352835275222:ios:5d2c56463bd781553bfc77',
    messagingSenderId: '352835275222',
    projectId: 'task-manager-b0625',
    storageBucket: 'task-manager-b0625.appspot.com',
    iosBundleId: 'com.example.plannerFrontend',
  );
}
